//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Border.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Border.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border is developed by.
        /// </summary>
        public static string About_Default_1 {
            get {
                return ResourceManager.GetString("About_Default_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as a test project to get AoE2 skills and broaden my programming skills. For the manual, reporting bugs, requesting features and the latest version checkout.
        /// </summary>
        public static string About_Default_2 {
            get {
                return ResourceManager.GetString("About_Default_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the project&apos;s page..
        /// </summary>
        public static string About_Default_3 {
            get {
                return ResourceManager.GetString("About_Default_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is provided &quot;as is&quot;, without warranty of any kind, express or implied..
        /// </summary>
        public static string About_Disclaimer {
            get {
                return ResourceManager.GetString("About_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string About_Translation {
            get {
                return ResourceManager.GetString("About_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual/About.
        /// </summary>
        public static string CM_About {
            get {
                return ResourceManager.GetString("CM_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string CM_AlwaysOnTop {
            get {
                return ResourceManager.GetString("CM_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoStepper.
        /// </summary>
        public static string CM_AutoStepper {
            get {
                return ResourceManager.GetString("CM_AutoStepper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Orders.
        /// </summary>
        public static string CM_BuildOrders {
            get {
                return ResourceManager.GetString("CM_BuildOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string CM_CheckForUpdates {
            get {
                return ResourceManager.GetString("CM_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Through Window.
        /// </summary>
        public static string CM_ClickThrough {
            get {
                return ResourceManager.GetString("CM_ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string CM_Compact {
            get {
                return ResourceManager.GetString("CM_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Build Order.
        /// </summary>
        public static string CM_NextBO {
            get {
                return ResourceManager.GetString("CM_NextBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string CM_NextTask {
            get {
                return ResourceManager.GetString("CM_NextTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Build Order.
        /// </summary>
        public static string CM_PrevBO {
            get {
                return ResourceManager.GetString("CM_PrevBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Step.
        /// </summary>
        public static string CM_PrevTask {
            get {
                return ResourceManager.GetString("CM_PrevTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string CM_Quit {
            get {
                return ResourceManager.GetString("CM_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string CM_Speed {
            get {
                return ResourceManager.GetString("CM_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string CM_Vertical {
            get {
                return ResourceManager.GetString("CM_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Build Orders Found!.
        /// </summary>
        public static string Title_NoBuildOrder {
            get {
                return ResourceManager.GetString("Title_NoBuildOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download latest Update Information. Please make sure this link is valid and you are connected to the internet..
        /// </summary>
        public static string Update_ConnectionError {
            get {
                return ResourceManager.GetString("Update_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your &apos;{0}&apos; file is missing. Please backup your builds and redownload the app..
        /// </summary>
        public static string Update_FileError {
            get {
                return ResourceManager.GetString("Update_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is available: &apos;{1}&apos;!.
        /// </summary>
        public static string Update_NewVersion {
            get {
                return ResourceManager.GetString("Update_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are up-to-date!.
        /// </summary>
        public static string Update_UpToDate {
            get {
                return ResourceManager.GetString("Update_UpToDate", resourceCulture);
            }
        }
    }
}
